### ISSUE TITLE
release_tool.py update doesn't work

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2518]
First test is:
```.log
scripts/release_tool.py init
Version to be created? [0.70.0] 
scripts/release_tool.py update build/uncrustify
Traceback (most recent call last):
  File "scripts/release_tool.py", line 243, in <module>
    sys.exit(main())
  File "scripts/release_tool.py", line 235, in main
    args.func(repo, args)
  File "scripts/release_tool.py", line 104, in cmd_update
    v = get_version_str(repo)
  File "scripts/release_tool.py", line 27, in get_version_str
    b = repo.git.branch('--show-current')
  File "/usr/lib/python2.7/dist-packages/git/cmd.py", line 551, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/git/cmd.py", line 1010, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/lib/python2.7/dist-packages/git/cmd.py", line 821, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
  cmdline: git branch --show-current
  stderr: 'error: unknown option `show-current'

```

**Comment by mwoehlke-kitware** [comment]
```
SYNOPSIS
       git branch [--color[=<when>] | --no-color] [--show-current]
```

Hmm... must be a recent addition? I'll see about finding an alternative...

**Comment by mwoehlke-kitware** [comment]
Does this work for you?
```
git symbolic-ref -q --short HEAD
```

(Should print the name of your active branch, or nothing if on a detached head.)

**Comment by guy-maurel** [comment]
Yes:
```.txt
git --version                                                          
git version 2.17.1
git symbolic-ref -q --short HEAD                                       
master
```

**Comment by mwoehlke-kitware** [comment]
Thanks for testing. Yeah, according to [SO](https://stackoverflow.com/a/56501750/1644352), `--show-current` is apparently new as of 2.22. #2519 should fix it (uses `git symbolic-ref -q --short HEAD` instead).
