### ISSUE TITLE
Segmentation fault with "align_func_proto_span = 1"

### ISSUE THREAD

**Issue by sebhub** [uncrustify/uncrustify#2960]
Uncrustify crashes with the following command line:

```
gdb --args uncrustify -c rtems.cfg threadqenqueue.c
...
(gdb) bt
#0  0x00000000004c87bb in std::_Deque_iterator<ChunkStack::Entry, ChunkStack::Entry&, ChunkStack::Entry*>::_M_set_node(ChunkStack::Entry**) ()
#1  0x00000000004e969b in std::_Deque_iterator<ChunkStack::Entry, ChunkStack::Entry&, ChunkStack::Entry*>::operator+=(long) ()
#2  0x00000000004e92f2 in std::_Deque_iterator<ChunkStack::Entry, ChunkStack::Entry&, ChunkStack::Entry*>::operator+(long) const ()
#3  0x00000000004e9331 in std::_Deque_iterator<ChunkStack::Entry, ChunkStack::Entry&, ChunkStack::Entry*>::operator[](long) const ()
#4  0x00000000004e90bf in std::deque<ChunkStack::Entry, std::allocator<ChunkStack::Entry> >::operator[](unsigned long) const ()
#5  0x00000000004e8c82 in ChunkStack::Get(unsigned long) const ()
#6  0x00000000004d5c27 in AlignStack::Debug() ()
#7  0x00000000004cd391 in align_func_proto(unsigned long) ()
#8  0x00000000004cbc9a in align_all() ()
#9  0x000000000059a2e2 in uncrustify_file(file_mem const&, _IO_FILE*, char const*, bool) ()
#10 0x0000000000598c32 in do_source_file(char const*, char const*, char const*, bool, bool) ()
#11 0x00000000005973a9 in main ()
```

https://gist.github.com/sebhub/4496ab03e6746c62659b729d2d768f82

**Comment by sebhub** [comment]
Version 0.71.0 works, it fails with bd11ada9a84645ae9a5bf02cdd5452f4b3063f0e.

**Comment by guy-maurel** [comment]
Servos
PR #2961 is a bugfix proposal.
Please test it and report.
