### ISSUE TITLE
Application crashed on destructor = default with any configuration

### ISSUE THREAD

**Issue by iohanaan** [uncrustify/uncrustify#3268]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Uncrustify app crashed with exception, when I try to format code which contains default destructor.
I used custom and default configuration with same result - crash with exception.

Test case:
```
Class::~Class() = default;
```

Exception:
```
terminate called after throwing an instance of 'std::out_of_range'                                 
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 1)
```

gdb backtrace:
```
(gdb) backtrace                                                                                
#0  0x00007ffff7446438 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff744803a in __GI_abort () at abort.c:89                                          
#2  0x00007ffff7a8cdde in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6                  
#3  0x00007ffff7a987a6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6                  
#4  0x00007ffff7a98811 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6    
#5  0x00007ffff7a98a65 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6         
#6  0x00007ffff7a8f4b1 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6                  
#7  0x00000000004daeb9 in ParseFrame::at(unsigned long) ()                                     
#8  0x000000000045e1bb in brace_cleanup() ()                                                   
#9  0x000000000050c5f1 in uncrustify_start(std::deque<int, std::allocator<int> > const&) ()    
#10 0x000000000050d3ea in uncrustify_file(file_mem const&, _IO_FILE*, char const*, bool) ()    
#11 0x000000000050ee5a in do_source_file(char const*, char const*, char const*, bool, bool) () 
#12 0x000000000043a870 in main ()                                                              
```

working version: Uncrustify-0.73.0

**Comment by guy-maurel** [comment]
You need to use the current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by iohanaan** [comment]
This bug does not appear on version Uncrustify-0.73.0-115-d584c28
