### ISSUE TITLE
bad change with release_tool.py

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#3895]
The change about args.keepversion make the use with 
`scripts/release_tool.py update ...`
impossible. I get an error message:
```.log
    Traceback (most recent call last):
      File "scripts/release_tool.py", line 286, in <module>
        sys.exit(main())
      File "scripts/release_tool.py", line 278, in main
        args.func(repo, args)
      File "scripts/release_tool.py", line 120, in cmd_update
        if args.keepversion:

```

**Comment by micheleCTDEAdmin** [comment]
Hi @guy-maurel 
I will have a look at this during the weekend or early next week.

**Comment by micheleCTDEAdmin** [comment]
Fxied by PR #3897.
